version: '3'

services:
  web-php:
    # image: php:8.3.3RC1-apache-bookworm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./phpAPI:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8084:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 1

volumes:
  db_data:
