USE todoList;
CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  date VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS doneTasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  date VARCHAR(255)
);
